version: '2.2'

services:
  mariadb:
    image: mariadb:latest
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: Root@1234
      MYSQL_DATABASE: quartz
      MYSQL_USER: quartz
      MYSQL_PASSWORD: Quartz@1234
      MYSQL_INITDB_SKIP_TZINFO: NONE
    ports:
      - 3306:3306
      - 33060:33060
    mem_limit: "512000000"
    networks:
      api-call-scheduler-nw:
        aliases:
          - mariadb
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 30s
      timeout: 60s
      retries: 10
    volumes:
      - mariadb_data:/var/lib/mysql
  scheduler:
    image: api-calls-scheduler:latest
    build:
      context: .
    restart: on-failure
    links:
      - mariadb
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      api-call-scheduler-nw:
        aliases:
          - scheduler
    ports:
      - 8880:8880
    environment:
      MYSQL_DATABASE_HOST: mariadb
      MYSQL_DATABASE_PORT: 3306
      MYSQL_DATABASE: quartz
      MYSQL_USER: quartz
      MYSQL_PASSWORD: Quartz@1234
      SPRING_PROFILES_ACTIVE: basic,external-mysql
      USER_TIMEZONE: IST
    healthcheck:
      test: ["CMD", "curl","-I" ,"-XGET", "http://localhost:8880/actuatot/health"]
      interval: 30s
      timeout: 30s
      retries: 15
    mem_limit: "1024000000"
volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: $PWD/container/persistence/mariadb
      o: bind
networks:
  api-call-scheduler-nw:
