version: '2.2'

services:
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: Keycloak@1234
      LOGSPOUT: ignore
    mem_limit: "512000000"
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak -d keycloak"]
      interval: 30s
      timeout: 15s
      retries: 10
    networks:
      keycloak-nw:
        aliases:
          - postgres
  keycloak:
    image: jboss/keycloak:latest
    healthcheck:
      test: ["CMD", "curl", "-I", "-XGET", "http://localhost:8080/auth/realms/master"]
      interval: 30s
      timeout: 30s
      retries: 15
    mem_limit: "1024000000"
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: Keycloak@1234
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Admin@1234
      LOGSPOUT: ignore
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
    volumes:
      - keycloak_realm_data:/tmp/migration
    command: ["-b 0.0.0.0", "-Dkeycloak.migration.action=import", "-Dkeycloak.migration.provider=singleFile", "-Dkeycloak.migration.file=/tmp/migration/master-realm.json", "-Dkeycloak.migration.strategy=IGNORE_EXISTING", "-Dkeycloak.profile.feature.upload_scripts=enabled"]
    ports:
      - 9990:8080
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      keycloak-nw:
        aliases:
          - keycloak
      api-call-scheduler-nw:
        aliases:
          - keycloak
  mariadb:
    image: mariadb:latest
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: Root@1234
      MYSQL_DATABASE: quartz
      MYSQL_USER: quartz
      MYSQL_PASSWORD: Quartz@1234
      MYSQL_INITDB_SKIP_TZINFO: NONE
    ports:
      - 3306:3306
      - 33060:33060
    mem_limit: "512000000"
    networks:
      api-call-scheduler-nw:
        aliases:
          - mariadb
    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-pRoot@1234' ]
      interval: 30s
      timeout: 60s
      retries: 10
    volumes:
      - mariadb_data:/var/lib/mysql
  scheduler:
    image: api-calls-scheduler:latest
    build:
      context: .
    restart: on-failure
    links:
      - mariadb
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      api-call-scheduler-nw:
        aliases:
          - scheduler
    ports:
      - 8880:8880
    environment:
      MYSQL_DATABASE_HOST: mariadb
      MYSQL_DATABASE_PORT: 3306
      MYSQL_DATABASE: quartz
      MYSQL_USER: quartz
      MYSQL_PASSWORD: Quartz@1234
      OAUTH2_USER_INFO_URL: http://keycloak:8080/auth/realms/conductor/protocol/openid-connect/userinfo
      SPRING_PROFILES_ACTIVE: basic,external-mysql,external-oauth2
      USER_TIMEZONE: IST
    healthcheck:
      test: ["CMD", "curl","-I" ,"-XGET", "http://localhost:8880/actuator/health"]
      interval: 30s
      timeout: 30s
      retries: 15
    mem_limit: "1024000000"
volumes:
  keycloak_realm_data:
    driver: local
    driver_opts:
      type: none
      device: $PWD/keycloak/migration
      o: bind
  postgres_data:
    driver: local
    driver_opts:
      type: none
      device: $PWD/container/persistence/postgres
      o: bind
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: $PWD/container/persistence/mariadb
      o: bind
networks:
  keycloak-nw:
  api-call-scheduler-nw:
