OAUTH2_USER_INFO_URL: http://keycloak:9990/auth/realms/conductor/protocol/openid-connect/userinfo
#https://localhost:9990/oauth/userinfo

oauth:
  security: EXTERNAL

security:
  oauth2:
    resource:
      userInfoUri: ${OAUTH2_USER_INFO_URL}
      mapping: |
        [
          {
            "endpoint": "/api/execution/**",
            "http_methods": [
              "POST",
              "PUT",
              "PATCH",
              "DELETE"
            ],
            "roles": [
              "role_scheduler_super_manager", "role_scheduler_execution_manager"
            ]
          },
          {
            "endpoint": "/api/execution/**",
            "http_methods": [
              "GET"
            ],
            "roles": [
              "role_scheduler_super_manager", "role_scheduler_super_viewer","role_scheduler_execution_manager", "role_scheduler_execution_viewer"
            ]
          },
          {
            "endpoint": "/api/metadata/**",
            "http_methods": [
              "POST",
              "PUT",
              "PATCH",
              "DELETE"
            ],
            "roles": [
              "role_scheduler_super_manager", "role_scheduler_core_manager"
            ]
          },
          {
            "endpoint": "/api/metadata/**",
            "http_methods": [
              "GET"
            ],
            "roles": [
              "role_scheduler_super_manager", "role_scheduler_super_viewer","role_scheduler_core_manager", "role_scheduler_core_viewer"
            ]
          }
        ]